// <auto-generated />
namespace VendeeCrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _544am : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_544am));
        
        string IMigrationMetadata.Id
        {
            get { return "201802232144253_544am"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
