// <auto-generated />
namespace VendeeCrop.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _731 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_731));
        
        string IMigrationMetadata.Id
        {
            get { return "201802211521299_7.3.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
